{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gmocoin-exec-alert.fullname" . }}
  labels:
    {{- include "gmocoin-exec-alert.labels" . | nindent 4 }}
type: Opaque
stringData:
  GMOCOIN_API_KEY: {{ .Values.gmocoin.apiKey | quote }}
  GMOCOIN_API_SECRET: {{ .Values.gmocoin.apiSecret | quote }}
  PAGERDUTY_ROUTING_KEY: {{ .Values.pagerduty.routingKey | quote }}
{{- end }}
